### ISSUE TITLE
Use formulaic-contrasts

### ISSUE THREAD

**Issue by grst** [const-ae/pyLemur#4]
### Description of feature

Hi @const-ae, 

I made some progress with making the `.cond()` logic we worked on during the Cambridge hackathon production-ready. There's now the [formulaic-contrasts](https://github.com/scverse/formulaic-contrasts) package providing a base class that can be used in custom models as described here: https://formulaic-contrasts.readthedocs.io/en/latest/model_usage.html
You could use that to get rid of a lot of custom code from this repo. It also deals with a lot more edge-cases than what we had stitched together during the hackathon. 

I also created documentation on how to work with `.cond()`: https://formulaic-contrasts.readthedocs.io/en/latest/contrasts.html. I'd appreciate if you could give it a quick read to check if I wrote something really dumb about linear models. 

Best, 
Gregor

**Comment by const-ae** [comment]
> There's now the [formulaic-contrasts](https://github.com/scverse/formulaic-contrasts) package providing a base class that can be used in custom models as described here: https://formulaic-contrasts.readthedocs.io/en/latest/model_usage.html

That looks great. Some small comments:

- In the model usage [section](https://formulaic-contrasts.readthedocs.io/en/latest/model_usage.html#via-inheritance), I would mention what arguments the constructor of `FormulaicConstrasts` needs.
- In the examples on the model usage section, you use interactions (`"~ treatment * response"`). I think it would be clearer to use a simple additive model without interactions.
- I think the `FormulaicContrasts.contrast` function should have some additional documentation how the contrast is formed for interaction models.
- I find the documentation of the return of `FormulaicContrasts.cond` a bit confusing. I would suggest:
     > A vector with one element per column in the design matrix, where the `kwargs` arguments are coded as in the design matrix.
- For a more didactic introduction of the [building contrast section](https://formulaic-contrasts.readthedocs.io/en/latest/contrasts.html), you could show how the design matrix looks. Otherwise I think it is very well written and easy to follow.

> You could use that to get rid of a lot of custom code from this repo. It also deals with a lot more edge-cases than what we had stitched together during the hackathon.

Excellent. I will try it out.

**Comment by const-ae** [comment]
In the [composition example](https://formulaic-contrasts.readthedocs.io/en/latest/model_usage.html#via-composition), should the method definition like this:

```python
def contrast(self, *args, **kwargs):
    return self.contrast_builder.contrast(*args, **kwargs)
```

Or should it be:
```python
def contrast(self, column, baseline, group_to_compare):
    return self.contrast_builder.contrast(column, baseline, group_to_compare)
```

**Comment by grst** [comment]
Thanks for your feedback, these are all very good points! 

> In the [composition example](https://formulaic-contrasts.readthedocs.io/en/latest/model_usage.html#via-composition), should the method definition of contrast be like this:

Both works, actually. `*args, **kwargs` is the most general way of delegating all arguments (positional or keyword) to another function. An advantage is that this would still work should other arguments be added to `contrast_builder.contrast`. 

The other approach is more explicit and automatically generated documentation might be easier to read.
